name: Nigthly release
on:
#  schedule:
#    - cron: '0 0 * * *'
  push:


jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop
      - uses: marceloprado/has-changed-path@v1
        id: check-if-changed
        with:
          paths: .github/workflows src/ res/ pom.xml .install4j/ .mvn/
      - name: Set up JDK 15
        if: steps.check-if-changed.outputs.changed == 'true'
        uses: actions/setup-java@v1
        with:
          java-version: 15

      - name: Cache local Maven repository
        if: steps.check-if-changed.outputs.changed == 'true'
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build and test with Maven
        if: steps.check-if-changed.outputs.changed == 'true'
        run: ./mvnw -B package
      - uses: actions/upload-artifact@v2
        with:
          name: target
          path: target/
      - name: SonarCloud Scan
        if: steps.check-if-changed.outputs.changed == 'true'
        run: ./mvnw -B org.jacoco:jacoco-maven-plugin:prepare-agent sonar:sonar -Dsonar.projectKey=mediathekview_MediathekView -Dsonar.organization=mediathekview -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  build:
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        include:
          - os: linux
            architecture: 64bit
            maven_profiles: "linux,64bit,install4j"
          - os: arm
            architecture: 32bit
            maven_profiles: "arm,!64bit,32bit,install4j,!linux"
          - os: windows
            architecture: 64bit
            maven_profiles: "windows,64bit,install4j,!linux"
          - os: windows
            architecture: 32bit
            maven_profiles: "windows32,!64bit,32bit,install4j,!linux"
          - os: macOS
            architecture: 64bit
            maven_profiles: "mac,!linux"
    steps:
      - uses: actions/checkout@v2
        if: needs.test.changed == 'true'
        with:
          ref: develop
      - name: Set up JDK 15
        if: needs.test.changed == 'true'
        uses: actions/setup-java@v1
        with:
          java-version: 15
      - uses: AdoptOpenJDK/install-jdk@v1
        if: needs.test.changed == 'true'
        with:
          version: '8'
          targets: 'INSTALL4J_JAVA_HOME'

      - name: Install install4j
        if: needs.test.changed == 'true'
        uses: teddyking/dependency-action@master
        with:
          deps: https://download-gcdn.ej-technologies.com/install4j/install4j_unix_8_0_9.tar.gz

      - name: Cache local Maven repository
        if: needs.test.changed == 'true'
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Add install4j license
        if: needs.test.changed == 'true'
        run: ./mvnw clean install4j:install-license -Pinstall4j
      - uses: actions/download-artifact@v2
        with:
          name: target

      - name: Building ${{ matrix.os }} ${{ matrix.architecture }} with Maven
        if: needs.test.changed == 'true'
        run: ./mvnw -B package -P${{ matrix.maven_profiles }} -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
      - name: Building AppImage
        if: matrix.os == 'linux' && needs.test.changed == 'true'
        run: scripte/appimage.sh
      - uses: actions/upload-artifact@v2
        if: needs.test.changed == 'true'
        with:
          name: release-target
          path: target/media/
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Get version
        if: needs.test.changed == 'true'
        run: echo "VERSION::$( ./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout )" >> $GITHUB_ENV
      - name: Set current date
        if: needs.test.changed == 'true'
        run: echo "NOW::$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV

      - uses: actions/download-artifact@v2
        if: needs.test.changed == 'true'
        with:
          name: release-target

      - name: Release
        if: needs.test.changed == 'true'
        uses: softprops/action-gh-release@v1
        with:
          name: ${VERSION}_${NOW}
          body_path: CHANGELOG.md
          prerelease: true
          files: |
            target/media/*.zip
            target/media/*.gz
            target/*.AppImage
            target/media/MediathekView*.exe
            target/media/*.deb
            target/media/*.rpm
            target/media/MediathekView*.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


